worldFields = ['name','description','notes']
ngiFields = ['title', 'description', 'notes', 'setting', 'genre','world']
chapterFields = ['title', 'description', 'notes', 'ngi', 'world', 'chapter_number']
sceneFields = ['description', 'notes', 'time_and_or_date', 'chapter', 'ngi', 'world']
characterFields = ['name', 'surname', 'age', 'gender', 'motive', 'description', 'world', 'scenes', 'chapters', 'ngi', 'acquaintances', 'notes']
locationFields = [ 'name', 'description', 'notes' ,'world' ,'ngi' ,'scenes', 'chapters']