# Generated by Django 3.1.5 on 2021-01-15 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_and_or_date', models.CharField(max_length=100)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='NarrativeGeneralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(max_length=2000)),
                ('genre', models.CharField(max_length=200)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.world')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapters', models.ManyToManyField(to='author.Chapter')),
                ('scenes', models.ManyToManyField(to='author.Scene')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=30)),
                ('motive', models.CharField(max_length=50)),
                ('acquaintances', models.ManyToManyField(related_name='_character_acquaintances_+', to='author.Character')),
                ('scenes', models.ManyToManyField(to='author.Scene')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='ngi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.narrativegeneralinfo'),
        ),
    ]
