# Generated by Django 3.1.5 on 2021-02-01 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('chapter_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NarrativeGeneralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('setting', models.CharField(blank=True, default='', max_length=2000)),
                ('genre', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('time_and_or_date', models.CharField(blank=True, default='', max_length=100)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='author.chapter')),
                ('ngi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='author.narrativegeneralinfo')),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='author.world')),
            ],
        ),
        migrations.AddField(
            model_name='narrativegeneralinfo',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='author.world'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('chapters', models.ManyToManyField(blank=True, to='author.Chapter')),
                ('ngi', models.ManyToManyField(to='author.NarrativeGeneralInfo')),
                ('scenes', models.ManyToManyField(blank=True, to='author.Scene')),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='author.world')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('surname', models.CharField(blank=True, default='', max_length=500)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, default='', max_length=30)),
                ('motive', models.CharField(blank=True, default='', max_length=50)),
                ('acquaintances', models.ManyToManyField(blank=True, related_name='_character_acquaintances_+', to='author.Character')),
                ('chapters', models.ManyToManyField(blank=True, to='author.Chapter')),
                ('ngi', models.ManyToManyField(blank=True, to='author.NarrativeGeneralInfo')),
                ('scenes', models.ManyToManyField(blank=True, to='author.Scene')),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='author.world')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='ngi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='author.narrativegeneralinfo'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='author.world'),
        ),
    ]
