# Generated by Django 3.1.5 on 2021-01-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrativegeneralinfo',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='narrativegeneralinfo',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='narrativegeneralinfo',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
